sudo: required
services:
  - docker

before_install:
  - docker build -t nitesh/docker-react -f Dockerfile.dev .

script:
  - docker run nitesh/docker-react npm run test -- --coverage

deploy:
  provider: azure_web_apps
  username: $AZURE_WA_USERNAME
  password: $AZURE_WA_PASSWORD
  site: "dockerwebsite"
  on:
    branch: master
 
    