sudo: required
services:
  - docker
  
deploy:
  provider: elasticbeanstalk
  app: "Docker"
  env: "Docker-env"
  region: "us-east-2"
  bucket_name: "elasticbeanstalk-us-east-2-308015402648"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_Key
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
    