sudo: required
services:
  - docker
before_install:
  - docker build -t nitesh/docker-react -f Dockerfile.dev .
script:
  - echo "deploy started"
deploy:
  provider: elasticbeanstalk
  app: "Docker"
  env: "Docker-env"
  region: "ap-south-1"
  bucket_name: "elasticbeanstalk-ap-south-1-308015402648"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
    